### ISSUE TITLE
nextPageToken missing

### ISSUE THREAD

**Issue by NicoHaase** [ali1234/ytsubs#6]
Hi there,
according to https://code.google.com/p/gdata-issues/issues/detail?id=7163, the nextPageToken is currently not returned from the API. Could you integrate static tokens as described in http://stackoverflow.com/a/30275747/1116230?
Regards
Nico

**Comment by ali1234** [comment]
Google seems to have fixed this now. It's working again for me anyway.

**Comment by NicoHaase** [comment]
Same here
